src/app/app.routing.ts
src/app/user-intent/user-intent-view/user-intent-view.component.html
src/app/user-intent/user-intent-view/user-intent-view.component.scss
src/app/user-intent/user-intent-view/user-intent-view.component.ts
src/app/user-intent/user-intent.component.html
src/app/user-intent/user-intent.component.ts
src/app/user-intent/user-intent.module.ts

adds dropdown for ecosystem, updates route structure

---

package.json
src/app/app.component.ts
src/app/app.routing.ts
src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.scss
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/stack-details/stack-details.module.ts
src/app/user-intent/user-intent-view/user-intent-view.component.html
src/app/user-intent/user-intent-view/user-intent-view.component.scss
src/app/user-intent/user-intent-view/user-intent-view.component.ts
src/app/user-intent/user-intent.component.html
src/app/user-intent/user-intent.component.scss
src/app/user-intent/user-intent.component.ts
src/app/user-intent/user-intent.module.ts
src/app/user-intent/user-intent.service.ts

adds user-intent component/modal/route

---

src/app/stack/stack-analyses.service.ts
src/app/stack/stack-details/stack-details.component.ts
src/app/user-intent/user-intent-view/user-intent-view.component.ts
src/app/user-intent/user-intent.service.ts

handle polling for stack analysis

---

src/app/stack/component-level/component-level.component.ts
src/app/stack/stack-details/stack-details.component.ts

fixes issue with licence , improves polling

---

src/app/user-intent/user-intent-view/user-intent-view.component.html
src/app/user-intent/user-intent-view/user-intent-view.component.scss
src/app/user-intent/user-intent-view/user-intent-view.component.ts

updates styles , text description

---

src/app/app.component.ts

updates url route to accept user-key

---

openshift/template.yaml

updates replicas to 3 and strartegy

---

Dockerfile.tests

fix Dockerfile.tests build
@samuzzal-choudhury @msrb

fix Dockerfile.tests build

---

src/app/app.component.ts
src/app/app.module.ts
src/app/stack/stack-analyses.service.ts
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/utils/component-feedback/component-feedback.component.ts
src/app/stack/utils/component-feedback/component-feedback.service.ts

Tracks : 
https://github.com/openshiftio/openshift.io/issues/4263

Fix feedback api

---

src/app/stack/card-details/card-details.component.ts
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
src/app/stack/models/ui.model.ts
src/app/stack/report-summary/report-summary.component.ts

- showing all cve IDs in stack report

fix(cve): showing all cve IDs in stack report

---

src/app/stack/card-details/card-details.component.ts
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.less
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.ts
src/app/stack/models/stack-report.model.ts
src/app/stack/models/ui.model.ts

- adds label in card to show last gitHub refreshed data

fix(lastupdated): adds label in card to show last gitHub refreshed data

---

src/app/stack/card-details/card-details.component.ts
src/app/stack/report-summary/report-summary.component.ts
src/app/stack/utils/report-summary-utils.ts
tests/spec/smoke.spec.js

- updates insights header to add-ons
Tracks : https://jira.coreos.com/browse/APPAI-591

fix(insights): updates insights header to add-ons

---

src/app/stack/report-summary/report-summary.component.ts

This PR fixes UI part of issue https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/336.

fix(transitive): Show transitive details only if transitive_count >= 0

---

src/app/stack/utils/report-summary-utils.ts

Mismatch between count for security issues and number of dependencies affected with the security issues

dependencies count added

---

.gitignore
package-lock.json
src/app/stack/card-details/card-details.component.ts
src/app/stack/utils/report-summary-utils.ts

Fixes issue https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/337.
```
connexion==2.3.0
flask==0.12
```

fix(transitive): Don't list transitive if it is already listed in direct

---

src/app/stack/card-details/card-details.component.ts
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.less
src/app/stack/card-details/report-information/report-information.component.less
src/app/stack/card-details/report-information/report-information.component.ts

Bugs covered :
- Expand Transitive list on clicking "Show Transitives with Vulnerabilities" text & text colour change.
- Focus on the blue button instead of white dialog (Remove shadow from Snyk sign up box).
- Change Headers(user # in place on "no of")
- Correction in the description of the security card.
- Progress bar colors need to match to the severity color
DevCluster URL: http://stack-report-ui-v2-shumathu-fabric8-analytics.devtools-dev.ext.devshift.net/

fix(bugs): bugs identified in bug bash round 3

---

src/app/stack/report-summary/report-summary-card/report-summary-content/report-info-entries/report-info-entries.component.html
src/app/stack/report-summary/report-summary-card/report-summary-content/report-info-entries/report-info-entries.component.less
src/app/stack/report-summary/report-summary.component.ts

bugfix: https://issues.redhat.com/browse/APPAI-1322

fix(bug): Dependency Details card text overflow to new line

---

src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html

bug : https://issues.redhat.com/browse/APPAI-1373
DevCluster URL: http://stack-report-ui-v2-shumathu-fabric8-analytics.devtools-dev.ext.devshift.net/#/analyze/613f71ae136142e8aaf967931017df8c?interframe=true&api_data={"access_token":"undefined","route_config":{"api_url":"https://f8a-analytics-preview-2445582058137.staging.gw.apicast.io","ver":"v2"},"user_key":"3e42fa66f65124e6b1266a23431e3d08"}

fix(bug): Recommended version incorrect

---

src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.less

Jira Bug: https://issues.redhat.com/browse/APPAI-1372
**SS#1**
> ![image](https://user-images.githubusercontent.com/23407383/86878947-b5f6be80-c107-11ea-993f-d6bd44181a2a.png)
**SS#2**
> ![image](https://user-images.githubusercontent.com/23407383/86878998-d0309c80-c107-11ea-8d06-ad806cc9d085.png)
**DevCluster URL**: http://stack-report-ui-v2-shumathu-fabric8-analytics.devtools-dev.ext.devshift.net/#/analyze/613f71ae136142e8aaf967931017df8c?interframe=true&api_data=%7B%22access_token%22%3A%22undefined%22%2C%22route_config%22%3A%7B%22api_url%22%3A%22https%3A%2F%2Ff8a-analytics-preview-2445582058137.staging.gw.apicast.io%22%2C%22ver%22%3A%22v2%22%7D%2C%22user_key%22%3A%223e42fa66f65124e6b1266a23431e3d08%22%7D

fix(bug): Text overflow from the tool-tip box

---

src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html

Jira issue: https://issues.redhat.com/browse/APPAI-1380
**SS with issue:**
> ![Screenshot from 2020-07-09 14-33-10](https://user-images.githubusercontent.com/23407383/87022269-e1ef6e00-c1f3-11ea-8283-eee3ae48107d.png)
**SS with the issue fixed:**
> ![Screenshot from 2020-07-09 14-53-23](https://user-images.githubusercontent.com/23407383/87022340-fa5f8880-c1f3-11ea-87e2-a3a3af1ac4e5.png)
**DevCluster URL:** http://stack-report-ui-v2-shumathu-fabric8-analytics.devtools-dev.ext.devshift.net/#/analyze/1db1cb32f55345c98f4029ae59e1ccf1?interframe=true&api_data=%7B%22access_token%22%3A%22undefined%22%2C%22route_config%22%3A%7B%22api_url%22%3A%22https%3A%2F%2Ff8a-analytics-preview-2445582058137.staging.gw.apicast.io%22%2C%22ver%22%3A%22v2%22%7D%2C%22user_key%22%3A%223e42fa66f65124e6b1266a23431e3d0 …

fix(issue): Recommended Version not shown in Add-ons card

---

src/app/stack/card-details/card-details.component.html
src/app/stack/card-details/card-details.component.ts
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
src/app/stack/card-details/report-information/report-information.component.html
src/app/stack/card-details/report-information/report-information.component.ts
src/app/stack/utils/handle-url.ts

Jira link: https://issues.redhat.com/browse/APPAI-1389

fix(issue): Added postMessage to handle url click in SA-UI

---

src/app/stack/card-details/card-details.component.html
src/app/stack/card-details/card-details.component.ts
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.less
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.ts
src/app/stack/card-details/report-information/report-information.component.html
src/app/stack/card-details/report-information/report-information.component.ts
src/app/stack/models/stack-report.model.ts
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/utils/url-generator.ts

**SS#1**
Commonly Known Vulnerabilities when the user is registered
**SS#2**
Vulnerabilities unique to Snyk when the user is registered
**SS#3**
Dependency Details Card
Value of Undefined will be populated when the response will have the value of the exploit

feat : View premium fields for registered user

---

src/app/stack/card-details/component-information/component-information.component.html
src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.ts

> https://issues.redhat.com/browse/APPAI-1500
> https://issues.redhat.com/browse/APPAI-1501
> https://issues.redhat.com/browse/APPAI-1503
> https://issues.redhat.com/browse/APPAI-1504
> https://issues.redhat.com/browse/APPAI-1505
> https://issues.redhat.com/browse/APPAI-1506
> https://issues.redhat.com/browse/APPAI-1507

Fix : Bug bash 18-09 fixes 

---

src/app/stack/card-details/card-details.component.html
src/app/stack/card-details/component-information/component-information.component.less
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.less
src/app/stack/card-details/component-information/component-snippet/component-snippet.component.ts
src/app/stack/models/stack-report.model.ts
src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/utils/url-generator.ts

fix:  User Management: Bug Bash 25-09

---

src/app/stack/stack-details/stack-details.component.html
src/app/stack/utils/url-generator.ts

chore: Update Snyk user registration UTM and helper text for mac user

---

src/app/stack/card-details/component-information/component-information.component.html

fix: Unique to Snyk Highest Severity Vulnerability text issue

---

src/app/stack/card-details/component-information/component-information.component.html
src/app/stack/card-details/component-information/component-information.component.less

fix: Add word wrap to avoid text overflow

---

src/app/utils/utility.ts

Fix number of `vulnerable dependencies` in the Summary Card

Fix number of vulnerable dependencies in Summary Card

---

src/app/components/main-components/Table/Table.scss
src/app/components/main-components/Table/Table.tsx
src/app/utils/utility.ts

Display snyk icon against private Vulnerabilities

Display snyk icon against private Vulnerabilities 

---

src/app/components/main-components/Table/Table.tsx
src/app/utils/utility.ts

Display Exploit Information in Direct Vulnerabilities

Display exploit information in Direct Vulnerabilities

---

src/app/components/main-components/Table/Table.scss
src/app/components/main-components/Table/Table.tsx
src/app/components/main-components/Table/TableInterfaces.ts

Display Severity Icon with Severity

Display Severity Icon with Severity

---

src/app/components/main-components/Overview/Overview.tsx
src/app/components/main-components/Table/Table.tsx
src/app/components/main-components/Table/VersionDetails.tsx

display vulnerability pie chart

display vulnerability pie chart

---

src/app/components/main-components/Overview/Overview.tsx
src/app/components/main-components/Table/Table.tsx

display appropriate transitive vulnerability details and remove percentage in summary pi chart.

display appropriate transitive vulnerability details

---

src/app/components/main-components/Table/Table.tsx

display dependency information for all rows and not just two rows.

display dependency information for all rows

---

Dockerfile.rhel
build_deploy.rhel.sh

signed off by msawood@redhat.com

chore: added rhel based job 
